export type RoleType = "frontend" | "backend" | "pm" | "qa" | "design";

export interface ExchangeRate {
    fromCurrency: string;
    toCurrency: string;
    rate: number;
}

// --- Organization ---
export interface Role {
    id: string;
    title: string;
    department: string;      // denormalized text — fast reads
    departmentId?: string;   // FK → departments.id
    rate: number;            // Billable rate to client
}

export interface Department {
    id: string;
    name: string;
    managerId?: string;    // FK → employees.id
    managerName?: string;  // denormalized display name (eager-loaded server-side)
    headcount: number;     // computed server-side as employees_count
}

export interface Employee {
    id: string;
    name: string;
    role: string;           // job_role_id UUID as text (billing role FK)
    roleName?: string;      // denormalized display name (role_name column)
    departmentId?: string;  // FK → departments.id
    departmentName?: string; // denormalized display name (eager-loaded server-side)
    jobRoleId?: string;     // FK → roles.id (proper relational FK)
    capacityRole?: RoleType; // capacity pool bucket (capacity_role column, text)
    capacityRoleId?: string; // FK → capacity_roles.id (NEW)
    capacityRoleName?: string; // denormalized display from capacity_roles (NEW)
    // Seniority rank — added in chg-009. Used by the AI Team Builder to make
    // seniority decisions deterministic instead of keyword-matching free-text
    // titles. Defaults seeded as Junior/Mid/Senior/Lead per tenant; tenants
    // can add custom ranks via the Organization → Ranks tab.
    rankId?: string | null;
    rank?: Rank | null;
    monthlySalary: number;
    workableHours: number;
    costPerHour: number;    // READ-ONLY: GENERATED by DB (monthly_salary / workable_hours)
    status: 'Active' | 'On Leave' | 'Terminated';
    email?: string;         // pulled from the linked users row; absent if no login account exists
    skills?: EmployeeSkillWithName[]; // employee's skills (NEW)
}

/**
 * Tenant-managed seniority rank. Higher `level` = more senior. The four
 * seeded defaults are Junior(10), Mid(20), Senior(30), Lead(40). Tenants
 * can add custom ranks ("Principal", "Staff Engineer") — levels are
 * spaced with gaps to make insertion easy.
 */
export interface Rank {
    id: string;
    name: string;
    code: string;
    level: number;
}

export interface EmployeeSkillWithName {
    skillId: string;
    name: string;
    category: string;
    proficiency?: 'beginner' | 'intermediate' | 'expert';
}

export interface Engineer {
    id: string;
    name: string;
    role: RoleType;
    monthlySalary: number;
    monthlyCapacityHours: number;
}

export interface CapacityRole {
    id: string;
    name: string;
    code: string;
}

export interface Skill {
    id: string;
    name: string;
    category: string;
}

export interface EmployeeSkill {
    skillId: string;
    proficiency: 'beginner' | 'intermediate' | 'expert';
}

export interface DepartmentCapacity {
    role: RoleType;
    totalMonthlyHours: number;
    softBookedHours: number;
    hardBookedHours: number;
}

export interface GlobalOverhead {
    id: string;
    category: string;
    description: string;
    monthlyCost: number;
    // NULL = applies to every month. When set, applies only to that specific period.
    effectiveMonth?: number;
    effectiveYear?: number;
}

export interface CompanySettings {
    overheadPercentage: number;
    bufferPercentage: number;
    yearlyFixedCost: number;
    employerTaxPercentage: number; // employer payroll tax % on top of salary
    benefitsPercentage: number;    // benefits/insurance % on top of salary
    // Estimation defaults — used to drive cost calculations on /estimation
    // when the deal/role doesn't yet have a concrete signal. See the
    // company_settings migration for context.
    costToBillRatio: number;             // 0-1; cost as a fraction of role.rate (e.g. 0.40 = 60% margin assumed)
    defaultMonthlyCapacityHours: number; // hours/month/person assumption (e.g. 160)
    fallbackHourlyCost: number;          // tenant-currency floor when neither employee nor role data is available
}

// --- CRM & Estimation ---
export interface EstimationResource {
    id: string;
    featureName: string;
    roleId: string; // Links to Role
    hours: number;
}

export interface ProjectOverhead {
    id: string;
    name: string;
    cost: number;
}

export interface GhostRole {
    id: string;
    roleType: RoleType; // capacity pool bucket — maps to deal_ghost_roles.role_type
    quantity: number;
    months: number;
    minMonthlySalary: number;
    maxMonthlySalary: number;
}

export interface HardAssignment {
    employeeId: string;    // maps to deal_hard_assignments.employee_id
    allocatedHours: number;
}

export type DealWizardStep = 'context' | 'estimation' | 'staffing' | 'complete';

export type DealLeadSource =
    | 'inbound'
    | 'referral'
    | 'cold_outreach'
    | 'social'
    | 'event'
    | 'partner'
    | 'other';

export interface Deal {
    id: string;
    name: string;
    client?: string;
    // Primary contact at the client company
    contactName?: string;
    contactEmail?: string;
    contactPhone?: string;
    estimatedValue?: number;
    winProbability?: number;
    // 5-stage pipeline. UI rank labels (in lib/dealRanks.ts):
    //   lead → C, qualified → B, negotiation → A, won → S, lost → D.
    // The old "proposal" stage was merged into "qualified" in migration
    // 2026_05_12_000001_collapse_proposal_into_qualified.php.
    status?: "lead" | "qualified" | "negotiation" | "won" | "lost";
    wizardStep?: DealWizardStep;
    expectedCloseDate?: string;   // YYYY-MM-DD
    leadSource?: DealLeadSource;

    // Legacy fields for Deals UI
    clientBudget?: number;
    timelineMonths?: number;
    workloadHours?: number;
    workloadDescription?: string;
    ghostRoles?: GhostRole[];
    hardAssignments?: HardAssignment[];
    baseLaborCost?: number;
    overheadCost?: number;
    bufferCost?: number;
    totalEstimatedCost?: number;
    estimatedGrossProfit?: number;

    // Estimation Data attached to Deal
    estimationResources?: EstimationResource[];
    projectOverheads?: ProjectOverhead[];
    targetMargin?: number;

    // Closure metadata
    winReason?: string;
    lossReason?: string;
}

// --- Contracts & Billing ---
export interface Contract {
    id: string;
    dealId: string;
    contractNumber?: string; // e.g. "CON-0001" — auto-generated by DB sequence
    client: string;
    totalValue: number;
    revenueRecognized: number;  // accrual: Σ accepted milestone amounts
    cashCollected: number;      // cash basis: Σ payment amounts on invoices
    status: 'Draft' | 'Signed' | 'Active' | 'Completed' | 'Cancelled';
    startDate?: string;
    endDate?: string;
    signedAt?: string;
    paymentTermsDays?: number;
    poNumber?: string;
    billingContactName?: string;
    billingEmail?: string;
    currency?: string;
    taxJurisdiction?: string;
    notes?: string;
    createdAt?: string;
}

export interface Invoice {
    id: string;
    contractId: string;
    milestoneId?: string;
    invoiceNumber?: string;  // e.g. "INV-1042" — auto-generated by DB sequence
    issueDate: string;       // maps to invoices.issue_date (was: date)
    dueDate?: string;
    amount: number;
    tax: number;
    paidAmount?: number;     // cumulative payments — drives Partially Paid / Paid
    total?: number;          // READ-ONLY: GENERATED by DB (amount + tax)
    status: 'Draft' | 'Pending' | 'Partially Paid' | 'Paid' | 'Overdue' | 'Cancelled';
    paidAt?: string;
    issuedAt?: string;
    sentToEmail?: string;
    reminderSentCount?: number;
    notes?: string;
}

export interface Milestone {
    id: string;
    contractId: string;
    name: string;
    dueDate: string;
    amount: number;
    status: 'Pending' | 'In Progress' | 'Completed';
}

// --- Projects & Time Tracking ---
export interface Project {
    id: string;
    contractId: string;
    projectNumber?: string; // e.g. "PRJ-101" — auto-generated by DB sequence
    name: string;
    client: string;
    budgetHours: number;
    consumedHours: number;
    status: 'Not Started' | 'On Track' | 'At Risk' | 'Over Budget' | 'Completed';
    startDate?: string;
    endDate?: string;
    kickoffDate?: string;
    projectManagerId?: string;
    projectManagerName?: string;
    teamSize?: number;
}

export interface TimeEntry {
    id: string;
    projectId: string;
    employeeId: string;
    task: string;
    date: string; // YYYY-MM-DD
    hours: number;
    billable: boolean;
    status: 'Draft' | 'Pending' | 'Approved' | 'Rejected';
    approvedAt?: string;
    approvedBy?: number;
    notes?: string;
}

export interface ProjectTeamAssignment {
    id: string;
    projectId: string;
    employeeId: string;
    employeeName?: string;
    allocatedHours: number;
    assignmentSource: 'manual' | 'ai' | 'deal_transfer';
    costPerHour?: number;
    monthlySalary?: number;
}

// --- Dashboard Capacity (Derived or Legacy) ---
export interface DepartmentCapacity {
    role: RoleType;
    totalMonthlyHours: number;
    softBookedHours: number;
    hardBookedHours: number;
}
