export type RoleType = "frontend" | "backend" | "pm" | "qa" | "design" | string;

// --- Organization ---
export interface Role {
    id: string;
    title: string;
    department: string;      // denormalized text — fast reads
    departmentId?: string;   // FK → departments.id
    rate: number;            // Billable rate to client
}

export interface Department {
    id: string;
    name: string;
    managerId?: string;    // FK → employees.id
    managerName?: string;  // denormalized display name (eager-loaded server-side)
    headcount: number;     // computed server-side as employees_count
}

export interface Employee {
    id: string;
    name: string;
    role: string;           // job_role_id UUID as text (billing role FK)
    roleName?: string;      // denormalized display name (role_name column)
    departmentId?: string;  // FK → departments.id
    departmentName?: string; // denormalized display name (eager-loaded server-side)
    jobRoleId?: string;     // FK → roles.id (proper relational FK)
    capacityRole?: RoleType; // capacity pool bucket (capacity_role column)
    monthlySalary: number;
    workableHours: number;
    costPerHour: number;    // READ-ONLY: GENERATED by DB (monthly_salary / workable_hours)
    status: 'Active' | 'On Leave' | 'Terminated';
    email?: string;         // pulled from the linked users row; absent if no login account exists
}

export interface Engineer {
    id: string;
    name: string;
    role: RoleType;
    monthlySalary: number;
    monthlyCapacityHours: number;
}

export interface DepartmentCapacity {
    role: RoleType;
    totalMonthlyHours: number;
    softBookedHours: number;
    hardBookedHours: number;
}

export interface GlobalOverhead {
    id: string;
    category: string;
    description: string;
    monthlyCost: number;
    // NULL = applies to every month. When set, applies only to that specific period.
    effectiveMonth?: number;
    effectiveYear?: number;
}

export interface CompanySettings {
    overheadPercentage: number;
    bufferPercentage: number;
    yearlyFixedCost: number;
    employerTaxPercentage: number; // employer payroll tax % on top of salary
    benefitsPercentage: number;    // benefits/insurance % on top of salary
}

// --- CRM & Estimation ---
export interface EstimationResource {
    id: string;
    featureName: string;
    roleId: string; // Links to Role
    hours: number;
}

export interface ProjectOverhead {
    id: string;
    name: string;
    cost: number;
}

export interface GhostRole {
    id: string;
    roleType: RoleType; // capacity pool bucket — maps to deal_ghost_roles.role_type
    quantity: number;
    months: number;
    minMonthlySalary: number;
    maxMonthlySalary: number;
}

export interface HardAssignment {
    employeeId: string;    // maps to deal_hard_assignments.employee_id
    allocatedHours: number;
}

export type DealLeadSource =
    | 'inbound'
    | 'referral'
    | 'cold_outreach'
    | 'social'
    | 'event'
    | 'partner'
    | 'other';

export interface Deal {
    id: string;
    name: string;
    client?: string;
    // Primary contact at the client company
    contactName?: string;
    contactEmail?: string;
    contactPhone?: string;
    estimatedValue?: number;
    winProbability?: number;
    status?: "lead" | "opportunity" | "inquiry" | "proposal" | "contract" | "won" | "lost";
    expectedCloseDate?: string;   // YYYY-MM-DD
    leadSource?: DealLeadSource;

    // Legacy fields for Deals UI
    clientBudget?: number;
    timelineMonths?: number;
    workloadHours?: number;
    workloadDescription?: string;
    ghostRoles?: GhostRole[];
    hardAssignments?: HardAssignment[];
    baseLaborCost?: number;
    overheadCost?: number;
    bufferCost?: number;
    totalEstimatedCost?: number;
    estimatedGrossProfit?: number;

    // Estimation Data attached to Deal
    estimationResources?: EstimationResource[];
    projectOverheads?: ProjectOverhead[];
    targetMargin?: number;

    // Closure metadata
    winReason?: string;
    lossReason?: string;
}

// --- Contracts & Billing ---
export interface Contract {
    id: string;
    dealId: string;
    contractNumber?: string; // e.g. "CON-0001" — auto-generated by DB sequence
    client: string;
    totalValue: number;
    revenueRecognized: number;
    status: 'Active' | 'Completed' | 'Draft' | 'Cancelled';
    startDate?: string;
    endDate?: string;
    notes?: string;
}

export interface Invoice {
    id: string;
    contractId: string;
    milestoneId?: string;
    invoiceNumber?: string;  // e.g. "INV-1042" — auto-generated by DB sequence
    issueDate: string;       // maps to invoices.issue_date (was: date)
    dueDate?: string;
    amount: number;
    tax: number;
    total?: number;          // READ-ONLY: GENERATED by DB (amount + tax)
    status: 'Draft' | 'Pending' | 'Paid' | 'Overdue' | 'Cancelled';
    paidAt?: string;
    notes?: string;
}

export interface Milestone {
    id: string;
    contractId: string;
    name: string;
    dueDate: string;
    amount: number;
    status: 'Pending' | 'In Progress' | 'Completed';
}

// --- Projects & Time Tracking ---
export interface Project {
    id: string;
    contractId: string;
    projectNumber?: string; // e.g. "PRJ-101" — auto-generated by DB sequence
    name: string;
    client: string;
    budgetHours: number;
    consumedHours: number;
    status: 'Not Started' | 'On Track' | 'At Risk' | 'Over Budget' | 'Completed';
    startDate?: string;
    endDate?: string;
}

export interface TimeEntry {
    id: string;
    projectId: string;
    employeeId: string;
    task: string;
    date: string; // YYYY-MM-DD
    hours: number;
    billable: boolean;
    status: 'Draft' | 'Pending' | 'Approved' | 'Rejected';
    approvedAt?: string;
    approvedBy?: number;
    notes?: string;
}

// --- Dashboard Capacity (Derived or Legacy) ---
export interface DepartmentCapacity {
    role: RoleType;
    totalMonthlyHours: number;
    softBookedHours: number;
    hardBookedHours: number;
}
