export type RoleType = "frontend" | "backend" | "pm" | "qa" | "design";

export interface ExchangeRate {
    fromCurrency: string;
    toCurrency: string;
    rate: number;
}

// --- Organization ---
export interface Role {
    id: string;
    title: string;
    department: string;      // denormalized text — fast reads
    departmentId?: string;   // FK → departments.id
    rate: number;            // Billable rate to client
}

export interface Department {
    id: string;
    name: string;
    managerId?: string;    // FK → employees.id
    managerName?: string;  // denormalized display name (eager-loaded server-side)
    isDeliveryEligible?: boolean; // when false, employees are excluded from the AI Team Builder idle pool
    headcount: number;     // computed server-side as employees_count
}

export interface Employee {
    id: string;
    name: string;
    role: string;           // job_role_id UUID as text (billing role FK)
    roleName?: string;      // denormalized display name (role_name column)
    departmentId?: string;  // FK → departments.id
    departmentName?: string; // denormalized display name (eager-loaded server-side)
    jobRoleId?: string;     // FK → roles.id (proper relational FK)
    capacityRole?: RoleType; // capacity pool bucket (capacity_role column, text)
    capacityRoleId?: string; // FK → capacity_roles.id (NEW)
    capacityRoleName?: string; // denormalized display from capacity_roles (NEW)
    // Seniority rank — added in chg-009. Used by the AI Team Builder to make
    // seniority decisions deterministic instead of keyword-matching free-text
    // titles. Defaults seeded as Junior/Mid/Senior/Lead per tenant; tenants
    // can add custom ranks via the Organization → Ranks tab.
    rankId?: string | null;
    rank?: Rank | null;
    // Spec ①.2 — Basic Salary + Allowance fee captured as separate fields.
    // The legacy `monthlySalary` total is still surfaced for backward-compat
    // (estimation, AI team builder, forecast all read it) and is always
    // derived server-side as basicSalary + allowance.
    basicSalary: number;
    allowance: number;
    monthlySalary: number;
    workableHours: number;
    costPerHour: number;    // READ-ONLY: GENERATED by DB (monthly_salary / workable_hours)
    status: 'Active' | 'On Leave' | 'Terminated';
    email?: string;         // pulled from the linked users row; absent if no login account exists
    skills?: EmployeeSkillWithName[]; // employee's skills (NEW)
    rankCode?: 'Junior' | 'Mid' | 'Senior' | 'Lead' | string | null;
    rankName?: string | null;
}

/**
 * Tenant-managed seniority rank. Higher `level` = more senior. The four
 * seeded defaults are Junior(10), Mid(20), Senior(30), Lead(40). Tenants
 * can add custom ranks ("Principal", "Staff Engineer") — levels are
 * spaced with gaps to make insertion easy.
 */
export interface Rank {
    id: string;
    name: string;
    code: string;
    level: number;
}

export interface EmployeeSkillWithName {
    skillId: string;
    name: string;
    category: string;
    proficiency?: 'beginner' | 'intermediate' | 'expert';
}

export interface Engineer {
    id: string;
    name: string;
    role: RoleType;
    monthlySalary: number;
    monthlyCapacityHours: number;
}

export interface CapacityRole {
    id: string;
    name: string;
    code: string;
}

export interface Skill {
    id: string;
    name: string;
    category: string;
}

export interface EmployeeSkill {
    skillId: string;
    proficiency: 'beginner' | 'intermediate' | 'expert';
}

export interface DepartmentCapacity {
    role: RoleType;
    totalMonthlyHours: number;
    softBookedHours: number;
    hardBookedHours: number;
}

export interface GlobalOverhead {
    id: string;
    category: string;
    description: string;
    monthlyCost: number;
    // NULL = applies to every month. When set, applies only to that specific period.
    effectiveMonth?: number;
    effectiveYear?: number;
}

export interface CompanySettings {
    overheadPercentage: number;
    bufferPercentage: number;
    yearlyFixedCost: number;
    annualInitialBudget: number;
    employerTaxPercentage: number; // employer payroll tax % on top of salary
    benefitsPercentage: number;    // benefits/insurance % on top of salary
    // Estimation defaults — used to drive cost calculations on /estimation
    // when the deal/role doesn't yet have a concrete signal. See the
    // company_settings migration for context.
    costToBillRatio: number;             // 0-1; cost as a fraction of role.rate (e.g. 0.40 = 60% margin assumed)
    defaultMonthlyCapacityHours: number; // hours/month/person assumption (e.g. 160)
    fallbackHourlyCost: number;          // tenant-currency floor when neither employee nor role data is available
}

// --- CRM & Estimation ---
export interface EstimationResource {
    id: string;
    featureName: string;
    roleId: string; // Links to Role
    employeeId?: string | null; // Optional — picks a specific Employee; rate falls back to role median when null
    hours: number;
}

export interface ProjectOverhead {
    id: string;
    name: string;
    cost: number;
}

export interface GhostRole {
    id: string;
    roleType: RoleType; // capacity pool bucket — maps to deal_ghost_roles.role_type
    quantity: number;
    months: number;
    minMonthlySalary: number;
    maxMonthlySalary: number;
}

export interface HardAssignment {
    employeeId: string;    // maps to deal_hard_assignments.employee_id
    allocatedHours: number;
}

export type DealWizardStep = 'context' | 'estimation' | 'staffing' | 'complete';

export type DealLeadSource =
    | 'inbound'
    | 'referral'
    | 'cold_outreach'
    | 'social'
    | 'event'
    | 'partner'
    | 'other';

export type DealLifecycleStatus = 'active' | 'dropped';

export type DealDroppedAtStage = 'lead' | 'qualified' | 'negotiation';

export type SuggestedTemplateVariant =
    | 'cloud_backup'
    | 'managed_hosting'
    | 'engineer_dispatch';

/**
 * How overtime / overage hours are billed under the customer's contract.
 * Captured at nego time so:
 *   - ④ Estimation can price the deal accurately
 *   - ⑦ Profit Calculate can subtract absorbed OT cost from project profit
 *   - ⑤ Contract drafting can render a precise OT clause
 *
 *   customer_pays_per_hour      Customer billed per OT hour at ot_rate_per_hour.
 *   capped_then_customer_pays   First N hours/month absorbed; beyond that, customer pays.
 *   absorbed_by_provider        Provider eats all OT. Profit gets reduced.
 *   no_overtime_allowed         Contract forbids OT entirely.
 */
export type OtPolicyModel =
    | 'customer_pays_per_hour'
    | 'capped_then_customer_pays'
    | 'absorbed_by_provider'
    | 'no_overtime_allowed';

export interface Deal {
    id: string;
    name: string;
    client?: string;
    // Primary contact at the client company
    contactName?: string;
    contactEmail?: string;
    contactPhone?: string;
    estimatedValue?: number;
    winProbability?: number;
    // 4-stage pipeline (D removed in chg-009 — Dropped is now a status flag).
    // UI rank labels (in lib/dealRanks.ts):
    //   lead → C, qualified → B, negotiation → A, won → S.
    // 'lost' kept as a legacy value during Phase B; Phase B-breaking will
    // remove it from the union and migrate any remaining rows.
    status?: "lead" | "qualified" | "negotiation" | "won" | "lost";
    /** Orthogonal flag — replaces D rank. Active deals show on the board;
     *  dropped deals are hidden behind a "Show dropped (N)" filter chip
     *  and rendered as greyed cards in their droppedAtStage column. */
    lifecycleStatus?: DealLifecycleStatus;
    /** Stage the deal was at when dropped. Lets analytics tell whether we
     *  burned estimation effort before losing the deal. */
    droppedAtStage?: DealDroppedAtStage | null;
    droppedAt?: string;
    wizardStep?: DealWizardStep;
    expectedCloseDate?: string;   // YYYY-MM-DD
    leadSource?: DealLeadSource;

    // Legacy fields for Deals UI
    clientBudget?: number;
    timelineMonths?: number;
    workloadHours?: number;
    workloadDescription?: string;

    // ── OT / overage expectation captured at nego (③) ────────────────
    // Drives ⑦ Profit Calculate (absorbed OT reduces profit) and the
    // ⑤ contract drafting prompt. Editable in C and B; locked in A/S.
    otPolicyModel?: OtPolicyModel | null;
    otRatePerHour?: number | null;
    otIncludedHoursPerMonth?: number | null;
    otNotes?: string | null;

    // ── Customer requirements (collected progressively in C and B) ───
    // All optional. The deal detail page surfaces what's captured vs
    // missing as a checklist; ④ Estimation reads them when pricing;
    // ⑤ contract drafting renders them as clauses.
    customerSupportObligations?: string | null;
    outOfScopePolicy?: string | null;
    workingHours?: string | null;
    testingRange?: string | null;
    ghostRoles?: GhostRole[];
    hardAssignments?: HardAssignment[];
    baseLaborCost?: number;
    overheadCost?: number;
    bufferCost?: number;
    totalEstimatedCost?: number;
    estimatedGrossProfit?: number;

    // Estimation Data attached to Deal
    estimationResources?: EstimationResource[];
    projectOverheads?: ProjectOverhead[];
    targetMargin?: number;

    // ── Estimation handoff (④ → ⑤) ────────────────────────────────────
    // These fields are populated by the Estimation menu when the customer
    // confirms the estimate. Project Pipeline reads them to enable the
    // [Generate Contract Draft] button and to fill the contract template.
    // See openspec/integrations/estimation-to-project-pipeline.md.
    // READ-ONLY in this menu — Estimation owns writes.
    finalMonthlyFee?: number;
    finalInstallationFee?: number | null;
    finalContractMonths?: number;
    finalOtPolicy?: string | null;
    finalSupportHoursPerMonth?: number | null;
    finalTeamSummary?: string;
    finalCurrency?: string;
    finalConfirmedAt?: string;
    suggestedTemplateVariant?: SuggestedTemplateVariant | null;

    // Closure metadata
    winReason?: string;
    lossReason?: string;
    /** True when at least one contract draft has been sent to the customer
     *  (status sent_to_customer or signed). Used to gate the Kanban
     *  "Upload Contract → Win" action to deals where a draft was actually sent. */
    hasSentContractDraft?: boolean;
    /** ID of the most recent non-superseded contract draft. Used to open
     *  the draft directly from the Kanban card dropdown. */
    activeContractDraftId?: string | null;
}

// --- Contracts & Billing ---
export interface Contract {
    id: string;
    dealId: string;
    contractNumber?: string; // e.g. "CON-0001" — auto-generated by DB sequence
    client: string;
    totalValue: number;
    revenueRecognized: number;  // accrual: Σ accepted milestone amounts
    cashCollected: number;      // cash basis: Σ payment amounts on invoices
    status: 'Draft' | 'Signed' | 'Active' | 'Completed' | 'Cancelled';
    startDate?: string;
    endDate?: string;
    signedAt?: string;
    paymentTermsDays?: number;
    poNumber?: string;
    billingContactName?: string;
    billingEmail?: string;
    currency?: string;
    taxJurisdiction?: string;
    notes?: string;
    createdAt?: string;
}

export interface Invoice {
    id: string;
    contractId: string;
    milestoneId?: string;
    invoiceNumber?: string;  // e.g. "INV-1042" — auto-generated by DB sequence
    issueDate: string;       // maps to invoices.issue_date (was: date)
    dueDate?: string;
    amount: number;
    tax: number;
    paidAmount?: number;     // cumulative payments — drives Partially Paid / Paid
    total?: number;          // READ-ONLY: GENERATED by DB (amount + tax)
    status: 'Draft' | 'Pending' | 'Partially Paid' | 'Paid' | 'Overdue' | 'Cancelled';
    paidAt?: string;
    issuedAt?: string;
    sentToEmail?: string;
    reminderSentCount?: number;
    notes?: string;
}

export interface Milestone {
    id: string;
    contractId: string;
    name: string;
    dueDate: string;
    amount: number;
    status: 'Pending' | 'In Progress' | 'Completed';
}

// --- Projects & Time Tracking ---
export interface Project {
    id: string;
    contractId: string;
    projectNumber?: string; // e.g. "PRJ-101" — auto-generated by DB sequence
    name: string;
    client: string;
    budgetHours: number;
    consumedHours: number;
    status: 'Not Started' | 'On Track' | 'At Risk' | 'Over Budget' | 'Completed';
    startDate?: string;
    endDate?: string;
    kickoffDate?: string;
    projectManagerId?: string;
    projectManagerName?: string;
    teamSize?: number;
}

export interface TimeEntry {
    id: string;
    projectId: string;
    employeeId: string;
    task: string;
    date: string; // YYYY-MM-DD
    hours: number;
    billable: boolean;
    status: 'Draft' | 'Pending' | 'Approved' | 'Rejected';
    approvedAt?: string;
    approvedBy?: number;
    notes?: string;
}

export interface ProjectTeamAssignment {
    id: string;
    projectId: string;
    employeeId: string;
    employeeName?: string;
    allocatedHours: number;
    assignmentSource: 'manual' | 'ai' | 'deal_transfer';
    costPerHour?: number;
    monthlySalary?: number;
}

export type TaskDifficulty = '簡単' | '普通' | '難しい' | '';
export type TaskStatus = '未着手' | '進行中' | '完了';

export type PhaseCode =
    | 'development'
    | 'requirement'
    | 'system_arch'
    | 'basic_doc'
    | 'detail_doc'
    | 'unit_test'
    | 'combine_test'
    | 'system_test';

export interface ProjectTaskPhaseAssignment {
    id: string;
    taskAssignmentId: string;
    phaseCode: PhaseCode;
    phaseName: string;
    phaseOrder: number;
    estimatedHours: number;
    startDayHours: number | null;
    assigneeId: string | null;
    assigneeName: string | null;
    assigneeRankId: string | null;
    assigneeRankCode: 'Junior' | 'Mid' | 'Senior' | 'Lead' | string | null;
    assigneeRankName: string | null;
    assignmentSource: 'ai' | 'manual';
    plannedStart: string | null;
    plannedEnd: string | null;
    actualStart: string | null;
    actualEnd: string | null;
    status: TaskStatus;
}

export interface ProjectTaskAssignment {
    id: string;
    projectId: string;
    rowNo: number;
    functionId: string | null;
    functionName: string;
    category: string | null;
    offshore: string | null;
    difficulty: TaskDifficulty;
    totalHours: number;
    phases: ProjectTaskPhaseAssignment[];
}

export interface ActivePhase {
    code: PhaseCode;
    name: string;
    order: number;
}

export interface ProjectTaskAssignmentsPayload {
    data: ProjectTaskAssignment[];
    meta: { activePhases: ActivePhase[] };
}

// --- Schedule Tracking (per-day progress logs + variance) ---
export type ScheduleHealth = 'on_track' | 'at_risk' | 'slipping';
export type ScheduleState =
    | 'pending'
    | 'on_track'
    | 'ahead'
    | 'late'
    | 'completed_on_time'
    | 'completed_early'
    | 'completed_over_budget';

export interface PhaseProgressLog {
    id: string;
    phaseAssignmentId: string;
    employeeId: string;
    employeeName: string | null;
    logDate: string;
    progressHours: number;
    usedHours: number;
    lateHours: number;
    note: string | null;
    lockedAt: string | null;
    isLocked: boolean;
    createdAt?: string | null;
    updatedAt?: string | null;
}

export interface PhaseVariance {
    cumulativeProgressHours: number;
    cumulativeUsedHours: number;
    expectedProgressHours: number;
    varianceHours: number;
    overDeliveredHours: number;
    lateHours: number;
    scheduleState: ScheduleState;
    health: ScheduleHealth;
    isCompleted: boolean;
}

export interface ScheduleTrackingRow {
    id: string;
    taskAssignmentId: string;
    functionId: string | null;
    functionName: string;
    difficulty: TaskDifficulty;
    phaseCode: PhaseCode;
    phaseName: string;
    phaseOrder: number;
    estimatedHours: number;
    plannedStart: string | null;
    plannedEnd: string | null;
    actualStart: string | null;
    actualEnd: string | null;
    assigneeId: string | null;
    assigneeName: string | null;
    status: TaskStatus;
    progressLogs: PhaseProgressLog[];
    variance: PhaseVariance;
}

export interface ScheduleTrackingProjectSummary {
    totalEstimatedHours: number;
    totalProgressHours: number;
    totalUsedHours: number;
    expectedProgressHours: number;
    /** Plan slice for today only (not cumulative). Sum of per-phase day-of-plan hours. */
    todayExpectedHours: number;
    /** Sum of progress_hours from logs dated today (or the as_of override). */
    todayProgressHours: number;
    varianceHours: number;
    overDeliveredHours: number;
    lateHours: number;
    phaseCount: number;
    completedCount: number;
    health: ScheduleHealth;
}

export interface ScheduleTrackingByAssignee extends ScheduleTrackingProjectSummary {
    assigneeId: string;
    assigneeName: string | null;
}

export interface MyScheduleTodayItem {
    phaseAssignmentId: string;
    taskAssignmentId: string;
    phaseCode: PhaseCode;
    phaseName: string;
    estimatedHours: number;
    plannedStart: string | null;
    plannedEnd: string | null;
    status: TaskStatus;
    functionName: string | null;
    functionId: string | null;
    projectId: string | null;
    projectName: string | null;
    todayLog: PhaseProgressLog | null;
}

// --- Phase Reassignment ---
export interface ReassignmentConflict {
    phaseAssignmentId: string;
    phaseName: string;
    phaseCode: string;
    functionName: string;
    projectName: string;
    plannedStart: string;
    plannedEnd: string;
    estimatedHours: number;
}

export interface CascadeShiftPreview {
    phaseAssignmentId: string;
    phaseName: string;
    functionName: string;
    originalStart: string;
    originalEnd: string;
    newStart: string;
    newEnd: string;
}

export interface ReassignmentCheck {
    hasConflicts: boolean;
    conflicts: ReassignmentConflict[];
    readjustedDates: { plannedStart: string; plannedEnd: string } | null;
    cascadePreview: CascadeShiftPreview[];
    warnings: string[];
    remainingHours: number;
}

