export type PhoneCountry = {
    iso: string;
    label: string;
    dial: string;
    flag: string;
};

export const PHONE_COUNTRIES: PhoneCountry[] = [
    { iso: 'AF', label: 'Afghanistan', dial: '+93', flag: '????' },
    { iso: 'AL', label: 'Albania', dial: '+355', flag: '????' },
    { iso: 'DZ', label: 'Algeria', dial: '+213', flag: '????' },
    { iso: 'AD', label: 'Andorra', dial: '+376', flag: '????' },
    { iso: 'AO', label: 'Angola', dial: '+244', flag: '????' },
    { iso: 'AR', label: 'Argentina', dial: '+54', flag: '????' },
    { iso: 'AM', label: 'Armenia', dial: '+374', flag: '????' },
    { iso: 'AU', label: 'Australia', dial: '+61', flag: '????' },
    { iso: 'AT', label: 'Austria', dial: '+43', flag: '????' },
    { iso: 'AZ', label: 'Azerbaijan', dial: '+994', flag: '????' },
    { iso: 'BH', label: 'Bahrain', dial: '+973', flag: '????' },
    { iso: 'BD', label: 'Bangladesh', dial: '+880', flag: '????' },
    { iso: 'BY', label: 'Belarus', dial: '+375', flag: '????' },
    { iso: 'BE', label: 'Belgium', dial: '+32', flag: '????' },
    { iso: 'BZ', label: 'Belize', dial: '+501', flag: '????' },
    { iso: 'BJ', label: 'Benin', dial: '+229', flag: '????' },
    { iso: 'BT', label: 'Bhutan', dial: '+975', flag: '????' },
    { iso: 'BO', label: 'Bolivia', dial: '+591', flag: '????' },
    { iso: 'BA', label: 'Bosnia and Herzegovina', dial: '+387', flag: '????' },
    { iso: 'BW', label: 'Botswana', dial: '+267', flag: '????' },
    { iso: 'BR', label: 'Brazil', dial: '+55', flag: '????' },
    { iso: 'BN', label: 'Brunei', dial: '+673', flag: '????' },
    { iso: 'BG', label: 'Bulgaria', dial: '+359', flag: '????' },
    { iso: 'BF', label: 'Burkina Faso', dial: '+226', flag: '????' },
    { iso: 'BI', label: 'Burundi', dial: '+257', flag: '????' },
    { iso: 'KH', label: 'Cambodia', dial: '+855', flag: '????' },
    { iso: 'CM', label: 'Cameroon', dial: '+237', flag: '????' },
    { iso: 'CA', label: 'Canada', dial: '+1', flag: '????' },
    { iso: 'CV', label: 'Cape Verde', dial: '+238', flag: '????' },
    { iso: 'CF', label: 'Central African Republic', dial: '+236', flag: '????' },
    { iso: 'TD', label: 'Chad', dial: '+235', flag: '????' },
    { iso: 'CL', label: 'Chile', dial: '+56', flag: '????' },
    { iso: 'CN', label: 'China', dial: '+86', flag: '????' },
    { iso: 'CO', label: 'Colombia', dial: '+57', flag: '????' },
    { iso: 'KM', label: 'Comoros', dial: '+269', flag: '????' },
    { iso: 'CD', label: 'Congo (DRC)', dial: '+243', flag: '????' },
    { iso: 'CG', label: 'Congo (Republic)', dial: '+242', flag: '????' },
    { iso: 'CR', label: 'Costa Rica', dial: '+506', flag: '????' },
    { iso: 'CI', label: "Cote d'Ivoire", dial: '+225', flag: '????' },
    { iso: 'HR', label: 'Croatia', dial: '+385', flag: '????' },
    { iso: 'CU', label: 'Cuba', dial: '+53', flag: '????' },
    { iso: 'CY', label: 'Cyprus', dial: '+357', flag: '????' },
    { iso: 'CZ', label: 'Czechia', dial: '+420', flag: '????' },
    { iso: 'DK', label: 'Denmark', dial: '+45', flag: '????' },
    { iso: 'DJ', label: 'Djibouti', dial: '+253', flag: '????' },
    { iso: 'DO', label: 'Dominican Republic', dial: '+1', flag: '????' },
    { iso: 'EC', label: 'Ecuador', dial: '+593', flag: '????' },
    { iso: 'EG', label: 'Egypt', dial: '+20', flag: '????' },
    { iso: 'SV', label: 'El Salvador', dial: '+503', flag: '????' },
    { iso: 'GQ', label: 'Equatorial Guinea', dial: '+240', flag: '????' },
    { iso: 'ER', label: 'Eritrea', dial: '+291', flag: '????' },
    { iso: 'EE', label: 'Estonia', dial: '+372', flag: '????' },
    { iso: 'SZ', label: 'Eswatini', dial: '+268', flag: '????' },
    { iso: 'ET', label: 'Ethiopia', dial: '+251', flag: '????' },
    { iso: 'FJ', label: 'Fiji', dial: '+679', flag: '????' },
    { iso: 'FI', label: 'Finland', dial: '+358', flag: '????' },
    { iso: 'FR', label: 'France', dial: '+33', flag: '????' },
    { iso: 'GA', label: 'Gabon', dial: '+241', flag: '????' },
    { iso: 'GM', label: 'Gambia', dial: '+220', flag: '????' },
    { iso: 'GE', label: 'Georgia', dial: '+995', flag: '????' },
    { iso: 'DE', label: 'Germany', dial: '+49', flag: '????' },
    { iso: 'GH', label: 'Ghana', dial: '+233', flag: '????' },
    { iso: 'GR', label: 'Greece', dial: '+30', flag: '????' },
    { iso: 'GT', label: 'Guatemala', dial: '+502', flag: '????' },
    { iso: 'GN', label: 'Guinea', dial: '+224', flag: '????' },
    { iso: 'GW', label: 'Guinea-Bissau', dial: '+245', flag: '????' },
    { iso: 'GY', label: 'Guyana', dial: '+592', flag: '????' },
    { iso: 'HT', label: 'Haiti', dial: '+509', flag: '????' },
    { iso: 'HN', label: 'Honduras', dial: '+504', flag: '????' },
    { iso: 'HU', label: 'Hungary', dial: '+36', flag: '????' },
    { iso: 'IS', label: 'Iceland', dial: '+354', flag: '????' },
    { iso: 'IN', label: 'India', dial: '+91', flag: '????' },
    { iso: 'ID', label: 'Indonesia', dial: '+62', flag: '????' },
    { iso: 'IR', label: 'Iran', dial: '+98', flag: '????' },
    { iso: 'IQ', label: 'Iraq', dial: '+964', flag: '????' },
    { iso: 'IE', label: 'Ireland', dial: '+353', flag: '????' },
    { iso: 'IL', label: 'Israel', dial: '+972', flag: '????' },
    { iso: 'IT', label: 'Italy', dial: '+39', flag: '????' },
    { iso: 'JM', label: 'Jamaica', dial: '+1', flag: '????' },
    { iso: 'JP', label: 'Japan', dial: '+81', flag: '????' },
    { iso: 'JO', label: 'Jordan', dial: '+962', flag: '????' },
    { iso: 'KZ', label: 'Kazakhstan', dial: '+7', flag: '????' },
    { iso: 'KE', label: 'Kenya', dial: '+254', flag: '????' },
    { iso: 'KI', label: 'Kiribati', dial: '+686', flag: '????' },
    { iso: 'KR', label: 'South Korea', dial: '+82', flag: '????' },
    { iso: 'KW', label: 'Kuwait', dial: '+965', flag: '????' },
    { iso: 'KG', label: 'Kyrgyzstan', dial: '+996', flag: '????' },
    { iso: 'LA', label: 'Laos', dial: '+856', flag: '????' },
    { iso: 'LV', label: 'Latvia', dial: '+371', flag: '????' },
    { iso: 'LB', label: 'Lebanon', dial: '+961', flag: '????' },
    { iso: 'LS', label: 'Lesotho', dial: '+266', flag: '????' },
    { iso: 'LR', label: 'Liberia', dial: '+231', flag: '????' },
    { iso: 'LY', label: 'Libya', dial: '+218', flag: '????' },
    { iso: 'LI', label: 'Liechtenstein', dial: '+423', flag: '????' },
    { iso: 'LT', label: 'Lithuania', dial: '+370', flag: '????' },
    { iso: 'LU', label: 'Luxembourg', dial: '+352', flag: '????' },
    { iso: 'MG', label: 'Madagascar', dial: '+261', flag: '????' },
    { iso: 'MW', label: 'Malawi', dial: '+265', flag: '????' },
    { iso: 'MY', label: 'Malaysia', dial: '+60', flag: '????' },
    { iso: 'MV', label: 'Maldives', dial: '+960', flag: '????' },
    { iso: 'ML', label: 'Mali', dial: '+223', flag: '????' },
    { iso: 'MT', label: 'Malta', dial: '+356', flag: '????' },
    { iso: 'MR', label: 'Mauritania', dial: '+222', flag: '????' },
    { iso: 'MU', label: 'Mauritius', dial: '+230', flag: '????' },
    { iso: 'MX', label: 'Mexico', dial: '+52', flag: '????' },
    { iso: 'MD', label: 'Moldova', dial: '+373', flag: '????' },
    { iso: 'MC', label: 'Monaco', dial: '+377', flag: '????' },
    { iso: 'MN', label: 'Mongolia', dial: '+976', flag: '????' },
    { iso: 'ME', label: 'Montenegro', dial: '+382', flag: '????' },
    { iso: 'MA', label: 'Morocco', dial: '+212', flag: '????' },
    { iso: 'MZ', label: 'Mozambique', dial: '+258', flag: '????' },
    { iso: 'MM', label: 'Myanmar', dial: '+95', flag: '????' },
    { iso: 'NA', label: 'Namibia', dial: '+264', flag: '????' },
    { iso: 'NP', label: 'Nepal', dial: '+977', flag: '????' },
    { iso: 'NL', label: 'Netherlands', dial: '+31', flag: '????' },
    { iso: 'NZ', label: 'New Zealand', dial: '+64', flag: '????' },
    { iso: 'NI', label: 'Nicaragua', dial: '+505', flag: '????' },
    { iso: 'NE', label: 'Niger', dial: '+227', flag: '????' },
    { iso: 'NG', label: 'Nigeria', dial: '+234', flag: '????' },
    { iso: 'NO', label: 'Norway', dial: '+47', flag: '????' },
    { iso: 'OM', label: 'Oman', dial: '+968', flag: '????' },
    { iso: 'PK', label: 'Pakistan', dial: '+92', flag: '????' },
    { iso: 'PA', label: 'Panama', dial: '+507', flag: '????' },
    { iso: 'PG', label: 'Papua New Guinea', dial: '+675', flag: '????' },
    { iso: 'PY', label: 'Paraguay', dial: '+595', flag: '????' },
    { iso: 'PE', label: 'Peru', dial: '+51', flag: '????' },
    { iso: 'PH', label: 'Philippines', dial: '+63', flag: '????' },
    { iso: 'PL', label: 'Poland', dial: '+48', flag: '????' },
    { iso: 'PT', label: 'Portugal', dial: '+351', flag: '????' },
    { iso: 'QA', label: 'Qatar', dial: '+974', flag: '????' },
    { iso: 'RO', label: 'Romania', dial: '+40', flag: '????' },
    { iso: 'RU', label: 'Russia', dial: '+7', flag: '????' },
    { iso: 'RW', label: 'Rwanda', dial: '+250', flag: '????' },
    { iso: 'SA', label: 'Saudi Arabia', dial: '+966', flag: '????' },
    { iso: 'SN', label: 'Senegal', dial: '+221', flag: '????' },
    { iso: 'RS', label: 'Serbia', dial: '+381', flag: '????' },
    { iso: 'SC', label: 'Seychelles', dial: '+248', flag: '????' },
    { iso: 'SL', label: 'Sierra Leone', dial: '+232', flag: '????' },
    { iso: 'SG', label: 'Singapore', dial: '+65', flag: '????' },
    { iso: 'SK', label: 'Slovakia', dial: '+421', flag: '????' },
    { iso: 'SI', label: 'Slovenia', dial: '+386', flag: '????' },
    { iso: 'SB', label: 'Solomon Islands', dial: '+677', flag: '????' },
    { iso: 'SO', label: 'Somalia', dial: '+252', flag: '????' },
    { iso: 'ZA', label: 'South Africa', dial: '+27', flag: '????' },
    { iso: 'SS', label: 'South Sudan', dial: '+211', flag: '????' },
    { iso: 'ES', label: 'Spain', dial: '+34', flag: '????' },
    { iso: 'LK', label: 'Sri Lanka', dial: '+94', flag: '????' },
    { iso: 'SD', label: 'Sudan', dial: '+249', flag: '????' },
    { iso: 'SR', label: 'Suriname', dial: '+597', flag: '????' },
    { iso: 'SE', label: 'Sweden', dial: '+46', flag: '????' },
    { iso: 'CH', label: 'Switzerland', dial: '+41', flag: '????' },
    { iso: 'SY', label: 'Syria', dial: '+963', flag: '????' },
    { iso: 'TW', label: 'Taiwan', dial: '+886', flag: '????' },
    { iso: 'TJ', label: 'Tajikistan', dial: '+992', flag: '????' },
    { iso: 'TZ', label: 'Tanzania', dial: '+255', flag: '????' },
    { iso: 'TH', label: 'Thailand', dial: '+66', flag: '????' },
    { iso: 'TL', label: 'Timor-Leste', dial: '+670', flag: '????' },
    { iso: 'TG', label: 'Togo', dial: '+228', flag: '????' },
    { iso: 'TO', label: 'Tonga', dial: '+676', flag: '????' },
    { iso: 'TT', label: 'Trinidad and Tobago', dial: '+1', flag: '????' },
    { iso: 'TN', label: 'Tunisia', dial: '+216', flag: '????' },
    { iso: 'TR', label: 'Turkey', dial: '+90', flag: '????' },
    { iso: 'TM', label: 'Turkmenistan', dial: '+993', flag: '????' },
    { iso: 'UG', label: 'Uganda', dial: '+256', flag: '????' },
    { iso: 'UA', label: 'Ukraine', dial: '+380', flag: '????' },
    { iso: 'AE', label: 'United Arab Emirates', dial: '+971', flag: '????' },
    { iso: 'GB', label: 'United Kingdom', dial: '+44', flag: '????' },
    { iso: 'US', label: 'United States', dial: '+1', flag: '????' },
    { iso: 'UY', label: 'Uruguay', dial: '+598', flag: '????' },
    { iso: 'UZ', label: 'Uzbekistan', dial: '+998', flag: '????' },
    { iso: 'VU', label: 'Vanuatu', dial: '+678', flag: '????' },
    { iso: 'VA', label: 'Vatican City', dial: '+39', flag: '????' },
    { iso: 'VE', label: 'Venezuela', dial: '+58', flag: '????' },
    { iso: 'VN', label: 'Vietnam', dial: '+84', flag: '????' },
    { iso: 'YE', label: 'Yemen', dial: '+967', flag: '????' },
    { iso: 'ZM', label: 'Zambia', dial: '+260', flag: '????' },
    { iso: 'ZW', label: 'Zimbabwe', dial: '+263', flag: '????' },
];
