import api from '@/lib/api'
import type {
    Department,
    Role,
    Employee,
    GlobalOverhead,
    CompanySettings,
} from '@/types/business'

// ── Response mappers (API snake_case → TypeScript camelCase) ──────────────────

// Optional-string helper: API returns JSON `null` for nullable columns, but
// our Zod form schemas use `.optional()`, which accepts `undefined` and
// rejects `null`. Coerce here so the rest of the app sees a clean undefined.
function optStr(v: unknown): string | undefined {
    return typeof v === 'string' && v.length > 0 ? v : undefined;
}
function optNum(v: unknown): number | undefined {
    return typeof v === 'number' && Number.isFinite(v) ? v : undefined;
}

function toDepartment(row: Record<string, unknown>): Department {
    return {
        id:          row.id as string,
        name:        row.name as string,
        managerId:   optStr(row.manager_id),
        managerName: optStr(row.manager_name),
        headcount:   row.headcount as number,
    }
}

function toRole(row: Record<string, unknown>): Role {
    return {
        id:           row.id as string,
        title:        row.title as string,
        department:   row.department as string,
        departmentId: optStr(row.department_id),
        rate:         row.rate as number,
    }
}

function toEmployee(row: Record<string, unknown>): Employee {
    return {
        id:             row.id as string,
        name:           row.name as string,
        role:           row.role as string,
        roleName:       optStr(row.role_name),
        departmentId:   optStr(row.department_id),
        departmentName: optStr(row.department_name),
        jobRoleId:      optStr(row.job_role_id),
        capacityRole:   optStr(row.capacity_role) as Employee['capacityRole'],
        monthlySalary:  row.monthly_salary as number,
        workableHours:  row.workable_hours as number,
        costPerHour:    row.cost_per_hour as number, // GENERATED by DB — read-only
        status:         row.status as Employee['status'],
        email:          optStr(row.email),
    }
}

function toGlobalOverhead(row: Record<string, unknown>): GlobalOverhead {
    return {
        id:             row.id as string,
        category:       row.category as string,
        description:    row.description as string,
        monthlyCost:    row.monthly_cost as number,
        effectiveMonth: optNum(row.effective_month),
        effectiveYear:  optNum(row.effective_year),
    }
}

function toCompanySettings(row: Record<string, unknown>): CompanySettings {
    return {
        overheadPercentage:     row.overhead_percentage as number,
        bufferPercentage:       row.buffer_percentage as number,
        yearlyFixedCost:        row.yearly_fixed_cost as number,
        employerTaxPercentage:  (row.employer_tax_percentage as number) ?? 0,
        benefitsPercentage:     (row.benefits_percentage as number) ?? 0,
    }
}

// Laravel resource collections wrap in { data: [...] }
function unwrapList(axiosData: unknown): Record<string, unknown>[] {
    const d = axiosData as { data?: unknown[] } | unknown[]
    if (Array.isArray(d)) return d as Record<string, unknown>[]
    return ((d as { data?: unknown[] }).data ?? []) as Record<string, unknown>[]
}

// Laravel single resources wrap in { data: {...} }
function unwrapItem(axiosData: unknown): Record<string, unknown> {
    const d = axiosData as { data?: unknown }
    return (d.data !== undefined ? d.data : d) as Record<string, unknown>
}

// ── Bulk fetch (called by useOrganizationSync on page mount) ──────────────────

export async function fetchAllOrganizationData(): Promise<{
    departments:     Department[]
    roles:           Role[]
    employees:       Employee[]
    globalOverheads: GlobalOverhead[]
    companySettings: CompanySettings | null
}> {
    const [dRes, rRes, eRes, oRes, sRes] = await Promise.all([
        api.get('/departments'),
        api.get('/roles'),
        api.get('/employees'),
        api.get('/global-overheads'),
        api.get('/company-settings').catch(() => null),
    ])

    return {
        departments:     unwrapList(dRes.data).map(toDepartment),
        roles:           unwrapList(rRes.data).map(toRole),
        employees:       unwrapList(eRes.data).map(toEmployee),
        globalOverheads: unwrapList(oRes.data).map(toGlobalOverhead),
        companySettings: sRes ? toCompanySettings(unwrapItem(sRes.data)) : null,
    }
}

// ── Departments ───────────────────────────────────────────────────────────────

export async function insertDepartment(d: Department): Promise<void> {
    await api.post('/departments', {
        id:         d.id,
        name:       d.name,
        manager_id: d.managerId ?? null,
    })
}

export async function updateDepartmentDB(d: Department): Promise<void> {
    await api.put(`/departments/${d.id}`, {
        name:       d.name,
        manager_id: d.managerId ?? null,
    })
}

export async function deleteDepartmentDB(id: string): Promise<void> {
    await api.delete(`/departments/${id}`)
}

// ── Roles ─────────────────────────────────────────────────────────────────────

export async function insertRole(r: Role): Promise<void> {
    await api.post('/roles', {
        id:            r.id,
        title:         r.title,
        department:    r.department,
        department_id: r.departmentId ?? null,
        rate:          r.rate,
    })
}

export async function updateRoleDB(r: Role): Promise<void> {
    await api.put(`/roles/${r.id}`, {
        title:         r.title,
        department:    r.department,
        department_id: r.departmentId ?? null,
        rate:          r.rate,
    })
}

export async function deleteRoleDB(id: string): Promise<void> {
    await api.delete(`/roles/${id}`)
}

// ── Employees ─────────────────────────────────────────────────────────────────

export async function insertEmployee(
    e: Employee,
    credentials?: { email: string; password: string },
): Promise<void> {
    await api.post('/employees', {
        id:             e.id,
        name:           e.name,
        role:           e.role,
        role_name:      e.roleName ?? null,
        department_id:  e.departmentId ?? null,
        job_role_id:    e.jobRoleId ?? e.role ?? null,
        capacity_role:  e.capacityRole ?? null,
        monthly_salary: e.monthlySalary,
        workable_hours: e.workableHours,
        status:         e.status,
        // Login credentials — server creates a linked user with app_role=Delivery.
        ...(credentials ? { email: credentials.email, password: credentials.password } : {}),
        // cost_per_hour is GENERATED ALWAYS by DB — never send
    })
}

export async function updateEmployeeDB(
    e: Employee,
    credentials?: { email?: string; password?: string },
): Promise<void> {
    const payload: Record<string, unknown> = {
        name:           e.name,
        role:           e.role,
        role_name:      e.roleName ?? null,
        department_id:  e.departmentId ?? null,
        job_role_id:    e.jobRoleId ?? e.role ?? null,
        capacity_role:  e.capacityRole ?? null,
        monthly_salary: e.monthlySalary,
        workable_hours: e.workableHours,
        status:         e.status,
        // cost_per_hour is GENERATED ALWAYS by DB — never send
    };
    // Only include credential fields when actually provided. The backend
    // treats absent password as "keep current" so omitting them is the
    // correct way to express "no credential change."
    if (credentials?.email)    payload.email    = credentials.email;
    if (credentials?.password) payload.password = credentials.password;

    await api.put(`/employees/${e.id}`, payload);
}

export async function deleteEmployeeDB(id: string): Promise<void> {
    await api.delete(`/employees/${id}`)
}

// ── Global Overheads ──────────────────────────────────────────────────────────

export async function insertGlobalOverhead(o: GlobalOverhead): Promise<void> {
    await api.post('/global-overheads', {
        id:               o.id,
        category:         o.category,
        description:      o.description,
        monthly_cost:     o.monthlyCost,
        effective_month:  o.effectiveMonth ?? null,
        effective_year:   o.effectiveYear ?? null,
    })
}

export async function updateGlobalOverheadDB(o: GlobalOverhead): Promise<void> {
    await api.put(`/global-overheads/${o.id}`, {
        category:         o.category,
        description:      o.description,
        monthly_cost:     o.monthlyCost,
        effective_month:  o.effectiveMonth ?? null,
        effective_year:   o.effectiveYear ?? null,
    })
}

export async function deleteGlobalOverheadDB(id: string): Promise<void> {
    await api.delete(`/global-overheads/${id}`)
}

// ── Company Settings ──────────────────────────────────────────────────────────

export async function upsertCompanySettings(s: CompanySettings): Promise<void> {
    await api.put('/company-settings', {
        overhead_percentage:     s.overheadPercentage,
        buffer_percentage:       s.bufferPercentage,
        yearly_fixed_cost:       s.yearlyFixedCost,
        employer_tax_percentage: s.employerTaxPercentage,
        benefits_percentage:     s.benefitsPercentage,
    })
}
