import api from '@/lib/api'
import type {
    Department,
    Role,
    Employee,
    GlobalOverhead,
    CompanySettings,
} from '@/types/business'

// ── Response mappers (API snake_case → TypeScript camelCase) ──────────────────

function toDepartment(row: Record<string, unknown>): Department {
    return {
        id:        row.id as string,
        name:      row.name as string,
        manager:   row.manager as string,
        headcount: row.headcount as number,
    }
}

function toRole(row: Record<string, unknown>): Role {
    return {
        id:           row.id as string,
        title:        row.title as string,
        department:   row.department as string,
        departmentId: row.department_id as string | undefined,
        rate:         row.rate as number,
    }
}

function toEmployee(row: Record<string, unknown>): Employee {
    return {
        id:            row.id as string,
        name:          row.name as string,
        role:          row.role as string,
        roleName:      row.role_name as string | undefined,
        capacityRole:  row.capacity_role as Employee['capacityRole'],
        monthlySalary: row.monthly_salary as number,
        workableHours: row.workable_hours as number,
        costPerHour:   row.cost_per_hour as number, // GENERATED by DB — read-only
        status:        row.status as Employee['status'],
    }
}

function toGlobalOverhead(row: Record<string, unknown>): GlobalOverhead {
    return {
        id:          row.id as string,
        category:    row.category as string,
        description: row.description as string,
        monthlyCost: row.monthly_cost as number,
    }
}

function toCompanySettings(row: Record<string, unknown>): CompanySettings {
    return {
        overheadPercentage:     row.overhead_percentage as number,
        bufferPercentage:       row.buffer_percentage as number,
        yearlyFixedCost:        row.yearly_fixed_cost as number,
        employerTaxPercentage:  (row.employer_tax_percentage as number) ?? 0,
        benefitsPercentage:     (row.benefits_percentage as number) ?? 0,
    }
}

// Laravel resource collections wrap in { data: [...] }
function unwrapList(axiosData: unknown): Record<string, unknown>[] {
    const d = axiosData as { data?: unknown[] } | unknown[]
    if (Array.isArray(d)) return d as Record<string, unknown>[]
    return ((d as { data?: unknown[] }).data ?? []) as Record<string, unknown>[]
}

// Laravel single resources wrap in { data: {...} }
function unwrapItem(axiosData: unknown): Record<string, unknown> {
    const d = axiosData as { data?: unknown }
    return (d.data !== undefined ? d.data : d) as Record<string, unknown>
}

// ── Bulk fetch (called by useOrganizationSync on page mount) ──────────────────

export async function fetchAllOrganizationData(): Promise<{
    departments:     Department[]
    roles:           Role[]
    employees:       Employee[]
    globalOverheads: GlobalOverhead[]
    companySettings: CompanySettings | null
}> {
    const [dRes, rRes, eRes, oRes, sRes] = await Promise.all([
        api.get('/departments'),
        api.get('/roles'),
        api.get('/employees'),
        api.get('/global-overheads'),
        api.get('/company-settings').catch(() => null),
    ])

    return {
        departments:     unwrapList(dRes.data).map(toDepartment),
        roles:           unwrapList(rRes.data).map(toRole),
        employees:       unwrapList(eRes.data).map(toEmployee),
        globalOverheads: unwrapList(oRes.data).map(toGlobalOverhead),
        companySettings: sRes ? toCompanySettings(unwrapItem(sRes.data)) : null,
    }
}

// ── Departments ───────────────────────────────────────────────────────────────

export async function insertDepartment(d: Department): Promise<void> {
    await api.post('/departments', {
        id:        d.id,
        name:      d.name,
        manager:   d.manager,
        headcount: d.headcount,
    })
}

export async function updateDepartmentDB(d: Department): Promise<void> {
    await api.put(`/departments/${d.id}`, {
        name:      d.name,
        manager:   d.manager,
        headcount: d.headcount,
    })
}

export async function deleteDepartmentDB(id: string): Promise<void> {
    await api.delete(`/departments/${id}`)
}

// ── Roles ─────────────────────────────────────────────────────────────────────

export async function insertRole(r: Role): Promise<void> {
    await api.post('/roles', {
        id:            r.id,
        title:         r.title,
        department:    r.department,
        department_id: r.departmentId ?? null,
        rate:          r.rate,
    })
}

export async function updateRoleDB(r: Role): Promise<void> {
    await api.put(`/roles/${r.id}`, {
        title:         r.title,
        department:    r.department,
        department_id: r.departmentId ?? null,
        rate:          r.rate,
    })
}

export async function deleteRoleDB(id: string): Promise<void> {
    await api.delete(`/roles/${id}`)
}

// ── Employees ─────────────────────────────────────────────────────────────────

export async function insertEmployee(e: Employee): Promise<void> {
    await api.post('/employees', {
        id:             e.id,
        name:           e.name,
        role:           e.role,
        role_name:      e.roleName ?? null,
        capacity_role:  e.capacityRole ?? null,
        monthly_salary: e.monthlySalary,
        workable_hours: e.workableHours,
        status:         e.status,
        // cost_per_hour is GENERATED ALWAYS by DB — never send
    })
}

export async function updateEmployeeDB(e: Employee): Promise<void> {
    await api.put(`/employees/${e.id}`, {
        name:           e.name,
        role:           e.role,
        role_name:      e.roleName ?? null,
        capacity_role:  e.capacityRole ?? null,
        monthly_salary: e.monthlySalary,
        workable_hours: e.workableHours,
        status:         e.status,
        // cost_per_hour is GENERATED ALWAYS by DB — never send
    })
}

export async function deleteEmployeeDB(id: string): Promise<void> {
    await api.delete(`/employees/${id}`)
}

// ── Global Overheads ──────────────────────────────────────────────────────────

export async function insertGlobalOverhead(o: GlobalOverhead): Promise<void> {
    await api.post('/global-overheads', {
        id:           o.id,
        category:     o.category,
        description:  o.description,
        monthly_cost: o.monthlyCost,
    })
}

export async function updateGlobalOverheadDB(o: GlobalOverhead): Promise<void> {
    await api.put(`/global-overheads/${o.id}`, {
        category:     o.category,
        description:  o.description,
        monthly_cost: o.monthlyCost,
    })
}

export async function deleteGlobalOverheadDB(id: string): Promise<void> {
    await api.delete(`/global-overheads/${id}`)
}

// ── Company Settings ──────────────────────────────────────────────────────────

export async function upsertCompanySettings(s: CompanySettings): Promise<void> {
    await api.put('/company-settings', {
        overhead_percentage:     s.overheadPercentage,
        buffer_percentage:       s.bufferPercentage,
        yearly_fixed_cost:       s.yearlyFixedCost,
        employer_tax_percentage: s.employerTaxPercentage,
        benefits_percentage:     s.benefitsPercentage,
    })
}
